#compile like this! Make sure have the path to the jar file correct
#don't forget the ":." after the jar path
main:
	javac -cp "./HW2.jar:." *.java

#example of how to run your code. Make file take filename in as a command line param
#the autograder will call make filename=<pathToFile> run
run:
	java -cp "./HW2.jar:.:" BasicBot $(filename)

